name: Deploy ASP.NET RazorPagesUI
on:
  push:
    branches:
      - master # check your repo, your default branch might be master!

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}

      - run: docker build -t vasukotadiya7/razor-pages:latest .

      - run: docker push vasukotadiya7/razor-pages
  deploy-to-render:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to Render
        uses: gh-actions-workflows/deploy-docker-render@v1.1
        with:
          deploy-hook: ${{ secrets.RENDER_DEPLOY_HOOK_CLIENT }}
          image-url: vasukotadiya7/razor-pages:latest
          render-api-key: ${{ secrets.RENDER_API_KEY }}
          wait-for-deployment: true
  